clear
echo -e "\033[38;5;208m"
echo -e "  __ _ _ __ ___ (_)_ __   "
echo -e " / _  |  _   _ \| |  __|  "
echo -e "| (_| | | | | | | | |     "
echo -e " \__,_|_| |_| |_|_|_|     "
echo -e "\e[34m"   
echo -e "\033[38;5;208m"                    "
echo -e "  ThisIsAmiR Best BOT Developer    "
echo -e "  MY Channel & Team : @OffLiNeTeam "
echo -e "  Me In Telegram : @This_Is_AmiR Messnger Bot : @This_Is_AmiRBot  "
echo -e "  Messnger Bot : @This_Is_AmiRBot  "
echo -e "\e[32m"
